open_servo_drive:
  description: "Open the servo drive (to position 100)"
  fields: {}

close_servo_drive:
  description: "Close the servo drive (to position 0)"
  fields: {}

set_servo_drive_position:
  description: "Set the position of the servo drive (0 to 100)"
  fields:
    position:
      description: "Position of the servo drive"
      example: 50

reset_servo_drive_position:
  description: "Rest the position of the servo drive to 50"
  fields: {}
